### ISSUE TITLE
Molecule version?

### ISSUE THREAD

**Issue by JeroenDeDauw** [gofrolist/molecule-action#4]
It'd be nice to have some info on the Molecule version used here.

I tried using this GH action to find it uses a Molecule version (2.x) incompatible with my project. This appears to not be changeable.

**Comment by gofrolist** [comment]
Yep, I know that Molecule 3.0 got release in 20 February 2020 and there are a lot of braking changes. So this is not only regarding version to provide but the structure of code also.
Probably it will be a different branch/tag in this action because I'm afraid if I will change it in master branch it can break some existing workflows which community are using.
Working on this

**Comment by gofrolist** [comment]
Created v2.0.0 with molecule 3.0.6 in it
use it like this:
`- uses: gofrolist/molecule-action@v2.0.0`
