### ISSUE TITLE
Add ability to override molecule version 

### ISSUE THREAD

**Issue by pavelpikta** [gofrolist/molecule-action#9]
Hi @gofrolist ,

I think it would be nice to add possibly override the version of the molecule

**Comment by gofrolist** [comment]
I agree but because this action is using prebuild docker image it's possible only based on docker tags and I need to create tags for every different version of molecule. Looks like a little bit complicated.
Another approach for this is to install molecule during build like geerlingguy are doing https://github.com/geerlingguy/ansible-role-postgresql/blob/master/.github/workflows/ci.yml
But in this case build will run a bit longer because for every run you will have to install molecule and dependencies.

So as you can see here is a trade off:
- install molecule during docker build and have built in molecule version but faster build time
- install molecule during github action and have molecule version as a variable but longer build time

**Comment by pavelpikta** [comment]
Thanks @gofrolist

**Comment by gardar** [comment]
I know this is an old issue but wouldn't it be possible to bundle multiple versions of ansible/molecule in the same container but in different virtualenvs? And then have some parameter in the action which chooses the appropriate virtualenv to use.

It would be highly beneficial to be able to select the ansible and molecule versions to use in the action config.

**Comment by gofrolist** [comment]
I believe it's possible, at least for molecule but for matrix of different versions molecule + ansible will bring a lot of complexity and size of the docker image will be huge
